name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
     
    - name: Login to DockerHub
      run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "gunareddy7" --password-stdin 
    
    - name: Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        path: docker/micro-sock
        dockerfile: ./Dockerfile
        registry: docker.io
        image: gunareddy7/micro-sock
    
